name: Tests

on:
    pull_request:
    push:
        branches:
        - master

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        resolver: [lts-16, lts-15, lts-14, lts-12]
        yaml: ['stack.yaml', 'stack-master.yaml']

    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles(matrix.yaml) }}-${{ hashFiles('xmonad-contrib.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles(matrix.yaml) }}-
            ${{ runner.os }}-${{ matrix.resolver }}-

      - name: Build and run tests
        shell: bash
        run: |
            set -ex
            curl -sSL https://get.haskellstack.org/ | sh -s - -f
            sudo apt install -y libasound2 libasound2-dev libxrandr-dev libtinfo-dev
            sudo apt install -y libx11-dev libgmp-dev libxss-dev libxft-dev
            stack --stack-yaml=${{ matrix.yaml }} test --fast --no-terminal --resolver=${{ matrix.resolver }}
